stages:
  - initial
  - scan
  - build
  - deploy
  - test

include:
  - project: 'iiidevops-templates/ci-template'
    ref: 'v2.1.5'
    file: 'job/Android.gitlab-ci.yml'
  - project: 'iiidevops-templates/ci-template'
    ref: 'v2.1.5'
    file: 'ci/template.gitlab-ci.yml'

Test--SonarQube source code scan:
  variables:
    iiidevops: sonarqube
    CHART_TYPE: gradle
    CHART_GRADLE_TAG: "jdk11"
  only:
  - master

Test--Checkmarx source code scan:
  variables:
    iiidevops: checkmarx
  only:
  - skip

.job-extend-android:
  variables:
    iiidevops: cmas
  only:
  - skip

Build--AndroidLintDebug:
  variables:
    iiidevops: deployed-environments
  only:
  - skip

Build--AndroidDebugApp:
  variables:
    iiidevops: deployed-environments
  only:
  - skip

Build image:
  variables:
    iiidevops: deployed-environments
    DOCKERFILE_PATH: Dockerfile
  needs:
  - Build--AndroidLintDebug
  - Build--AndroidDebugApp
  only:
  - skip

Build--Scan docker image:
  variables:
    iiidevops: deployed-environments
  only:
  - skip

Deploy--Set environment and wait deployment:
  variables:
    iiidevops: deployed-environments
  only:
  - skip

Deploy--Web:
  variables:
    iiidevops: deployed-environments
    CHART_WEB_PORT: 80
    CHART_PROXY_BODY_SIZE: 1m
  only:
  - skip

Test--Anchore SBOM:
  variables:
    iiidevops: anchore
  only:
  - skip

Test--AndroidTestDebug:
  variables:
    iiidevops: cmas
  only:
  - skip

Test--CMAS APK scan:
  variables:
    iiidevops: cmas
    CHART_NAME: "${CI_PROJECT_NAME}-${CI_COMMIT_BRANCH}-cmas"
    CHART_VERSION: "0.0.5"
    CMAS_A_MODE: "24"
    CMAS_A_ERT: "90"
  only:
  - skip