include:
- project: iiidevops-templates/ci-template
  ref: v2.8.0
  file: ci/template.gitlab-ci.yml
- project: 'iiidevops-templates/ci-template'
  ref: v2.8.0
  file: 'job/Android.gitlab-ci.yml'
- local: iiidevops/jobs/*.yml

stages:
- initial
- scan
- build
- deploy
- test
- userjobs

Test--SonarQube source code scan:
  variables:
    iiidevops: sonarqube
    CHART_TYPE: gradle
    CHART_GRADLE_TAG: "jdk17"

Test--Anchore SBOM source code scan:
  variables:
    iiidevops: anchore-code

Test--Anchore SBOM source code scan:
  variables:
    iiidevops: anchore-code

Test--Checkmarx source code scan:
  variables:
    iiidevops: checkmarx

.job-extend-android:
  variables:
    iiidevops: cmas

Build--AndroidLintDebug:
  variables:
    iiidevops: build

Build--AndroidDebugApp:
  variables:
    iiidevops: build

Build image:
  variables:
    iiidevops: build
    DOCKERFILE_PATH: Dockerfile
  needs:
  - Build--AndroidLintDebug
  - Build--AndroidDebugApp

Build--Scan docker image:
  variables:
    iiidevops: build

Deploy--Set environment and wait deployment:
  variables:
    iiidevops: deploy

Deploy--Web:
  variables:
    iiidevops: deploy
    CHART_WEB_PORT: 80
    CHART_PROXY_BODY_SIZE: 1m
    CHART_VOLUME_ENABLED: 'false'
    CHART_VOLUME_PATH: "/usr/src"

Test--Anchore SBOM:
  variables:
    iiidevops: anchore

Test--AndroidTestDebug:
  variables:
    iiidevops: cmas

Test--CMAS APK scan:
  variables:
    iiidevops: cmas
    CHART_NAME: "${CI_PROJECT_NAME}-${CI_COMMIT_BRANCH}-cmas"
    CHART_VERSION: "0.0.5"
    CMAS_A_MODE: "24"
    CMAS_A_ERT: "90"